CONTRIBUTING.rst, requirements_dev.txt, setup.py, tests/test_cli.py, tests/test_zigzag.py, zigzag/zigzag.py
Add a "junit.xml" file attachment to each test log so that raw results can be
inspected if qTest shows a difference in results.
=> ASC-350 Attach Raw JUnit XML Files to Test Logs

tests/conftest.py, tests/test_zigzag.py, zigzag/zigzag.py
Attach "build_url" and "build_number" to qTest test log results. Also,
refactored the expected environment variables to match the changes in
"pytest-rpc" plug-in.
=>  ASC-348 Add Build Info to qTest Results 

Makefile, requirements_dev.txt, setup.cfg, setup.py, tests/conftest.py, tests/test_zigzag.py, zigzag/__init__.py, zigzag/zigzag.py
Before loading processing XML files, zigzag will first check compliance with
the XSD from the "pytest-rpc" project.
Bumped the version to 0.6.0.
=> ASC-368 Validate JUnitXML Against XSD

CONTRIBUTING.rst, Makefile
Updated the makefile to make it possible to run most tasks without having
"virtualenvwrapper" installed or configured. Also, updated the documentation
to clarify which Makefile tasks can be executed without "virtualenvwrapper".
=>  ASC-375 Makefile Should Work without Virtualenvwrapper 

tests/conftest.py, tests/test_cli.py, tests/test_zigzag.py, zigzag/cli.py, zigzag/zigzag.py
With this new command-line option enabled a debug print-out of the JUnitXML
file will be displayed on screen when a schema violation occurs.
=> ASC-392 Pretty Print XML on Schema Failure

zigzag/zigzag.py
Changed the order of the collection of test log properties so that the test
name will always be captured in failure messages.
=> ASC-455 Fix for Test Name Missing from Failure Message

tests/conftest.py, tests/test_zigzag.py, zigzag/zigzag.py
Loosen the regex for the "classname" attribute to allow for dashes in the
"py.test" filename.
=> ASC-456 Fix to Allow Dashes in "py.test" Filenames

setup.cfg, tests/test_cli.py, tests/test_zigzag.py, zigzag/cli.py, zigzag/zigzag.py
In order to make zigzag more flexible to reduce changes to CI jobs the
automatic discovery of the root test cycles parent has been implemented.
The cmdline interface was updated to change the required test cycle argument
into an option.
=> ASC-437 Auto-discover Test Cycle Parent

README.rst
Need to revert because the reference is to "docs", but the actual directory is called "doc".
=> Revert "ASC-399 add link to docs in README"

tests/unit/test_zigzag.py, tests/unit/test_zigzag_test_log.py, zigzag/zigzag_test_log.py
Prior to this change a very long log output string could be
put in the qtest failure output field. This can throw off the
page layout.
This update truncates the log if it's over some character limit
and refers the user to the attached text file containing the
log output.
=> ASC-761 add a failure log summary

zigzag/zigzag_test_log.py
Prior to this fix, the failure output
attachment was getting truncated by the work
done in asc-761.
This commit creates a new variable to
hold the unabridged log so it can be
preserved and stored in the attachment.
=> ASC-761 log output attachemnt truncated

tests/unit/test_link_generation_facade.py, zigzag/link_generation_facade.py, zigzag/zigzag_test_log.py
- changes Failure link calculation to be based on git SHA
- failure line number determined with full_failure_output property
=> ASC-890 base GitHub link on SHA

tests/integration/conftest.py, tests/integration/test_basic.py
Add integration tests that cover expected behavior when an automation engineer
renames or moves a test case within a given Git repo under test.
Also, I discovered more bugs and small typos that are fixed in this commit.
=> ASC-441 Add Test Case Rename/Move Integration Tests

tests/integration/conftest.py, tests/integration/test_failure_output.py, tests/integration/test_github_linking.py
Add test cases for validating links to GitHub being generated upon test
failure.
=> ASC-796 Add Failure Linking Integration Tests

Makefile, docs/release_process.rst, tests/data/junit.xml.j2, tests/integration/conftest.py, tests/integration/test_negative.py, tox.ini, zigzag/zigzag_test_log.py
Turns out that running ZigZag under Python 3.x breaks everything. :(
This commit fixes the underlying issue while also updating the integration test
suite for Python 3.x compatibility. Furthermore, the Makefile and release
process documentation have been updated to ensure that all tests are ran before
release.
=> ASC-864 Fix Crash on Failure Attachment

tests/integration/test_failure_output.py, tests/unit/test_zigzag_test_log.py, zigzag/zigzag_test_log.py
In order to provide more useful failure output in the qTest interface, the
"Failure Output" field will now show truncated output from the bottom up from
the failure point.
=> ASC-867 Improve Failure Output Truncation

zigzag/zigzag.py
- changes zigzag __init__ to explicitly expect None for qtest_test_cycle
=> ASC-953 make None more explicitly expected

zigzag/data/mk8s_junit.xsd, zigzag/data/molecule_junit.xsd
The XSD is too strict and rejects valid JUnitXML files that contain multiple
"system-err"/"system-out" elements. Updated XSD to loosen validation.
=> ASC-1141 Update XSD to Allow for Multiple System Capture Elements

tests/unit/test_zigzag.py, zigzag/module_hierarchy_facade.py, zigzag/zigzag_test_log.py
A recent release of flake8 moved a PEP8 weak warning to strict warning which started causes flake8 violations on this project.
=> MAINT Fix flake8 Violations

tests/integration/test_steps.py, tests/unit/test_zigzag_test_log.py, zigzag/zigzag_test_log.py
- refactors classes related to _ZigZagTestLog
- removes _parse methods
- makes properties lazy load (saves us from having to worry about order of operations)
- caches the values of some of the properties
=> ASC-1199 refactor _ZigZagTestLog

README.rst
Most of the documentation was already added as part of
f2a38d59b60960cc3a5bae05fc749820b2dd6f19
While reviewing that change I found that the arguments
in the command line example are reversed. This commit
fixes that example.
=> ASC-1280 Document "zigzag" Configuration Mechanism
